/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZaufanieRouteImport } from './routes/zaufanie'
import { Route as ZajeciaWGrupieRouteImport } from './routes/zajecia-w-grupie'
import { Route as UzytkowanieAutaRouteImport } from './routes/uzytkowanie-auta'
import { Route as NaszaGaleriaRouteImport } from './routes/nasza-galeria'
import { Route as GodzinaWyjsciaRouteImport } from './routes/godzina-wyjscia'
import { Route as GodzinaPrzyjazduRouteImport } from './routes/godzina-przyjazdu'
import { Route as IndexRouteImport } from './routes/index'

const ZaufanieRoute = ZaufanieRouteImport.update({
  id: '/zaufanie',
  path: '/zaufanie',
  getParentRoute: () => rootRouteImport,
} as any)
const ZajeciaWGrupieRoute = ZajeciaWGrupieRouteImport.update({
  id: '/zajecia-w-grupie',
  path: '/zajecia-w-grupie',
  getParentRoute: () => rootRouteImport,
} as any)
const UzytkowanieAutaRoute = UzytkowanieAutaRouteImport.update({
  id: '/uzytkowanie-auta',
  path: '/uzytkowanie-auta',
  getParentRoute: () => rootRouteImport,
} as any)
const NaszaGaleriaRoute = NaszaGaleriaRouteImport.update({
  id: '/nasza-galeria',
  path: '/nasza-galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const GodzinaWyjsciaRoute = GodzinaWyjsciaRouteImport.update({
  id: '/godzina-wyjscia',
  path: '/godzina-wyjscia',
  getParentRoute: () => rootRouteImport,
} as any)
const GodzinaPrzyjazduRoute = GodzinaPrzyjazduRouteImport.update({
  id: '/godzina-przyjazdu',
  path: '/godzina-przyjazdu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/godzina-przyjazdu': typeof GodzinaPrzyjazduRoute
  '/godzina-wyjscia': typeof GodzinaWyjsciaRoute
  '/nasza-galeria': typeof NaszaGaleriaRoute
  '/uzytkowanie-auta': typeof UzytkowanieAutaRoute
  '/zajecia-w-grupie': typeof ZajeciaWGrupieRoute
  '/zaufanie': typeof ZaufanieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/godzina-przyjazdu': typeof GodzinaPrzyjazduRoute
  '/godzina-wyjscia': typeof GodzinaWyjsciaRoute
  '/nasza-galeria': typeof NaszaGaleriaRoute
  '/uzytkowanie-auta': typeof UzytkowanieAutaRoute
  '/zajecia-w-grupie': typeof ZajeciaWGrupieRoute
  '/zaufanie': typeof ZaufanieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/godzina-przyjazdu': typeof GodzinaPrzyjazduRoute
  '/godzina-wyjscia': typeof GodzinaWyjsciaRoute
  '/nasza-galeria': typeof NaszaGaleriaRoute
  '/uzytkowanie-auta': typeof UzytkowanieAutaRoute
  '/zajecia-w-grupie': typeof ZajeciaWGrupieRoute
  '/zaufanie': typeof ZaufanieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/godzina-przyjazdu'
    | '/godzina-wyjscia'
    | '/nasza-galeria'
    | '/uzytkowanie-auta'
    | '/zajecia-w-grupie'
    | '/zaufanie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/godzina-przyjazdu'
    | '/godzina-wyjscia'
    | '/nasza-galeria'
    | '/uzytkowanie-auta'
    | '/zajecia-w-grupie'
    | '/zaufanie'
  id:
    | '__root__'
    | '/'
    | '/godzina-przyjazdu'
    | '/godzina-wyjscia'
    | '/nasza-galeria'
    | '/uzytkowanie-auta'
    | '/zajecia-w-grupie'
    | '/zaufanie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GodzinaPrzyjazduRoute: typeof GodzinaPrzyjazduRoute
  GodzinaWyjsciaRoute: typeof GodzinaWyjsciaRoute
  NaszaGaleriaRoute: typeof NaszaGaleriaRoute
  UzytkowanieAutaRoute: typeof UzytkowanieAutaRoute
  ZajeciaWGrupieRoute: typeof ZajeciaWGrupieRoute
  ZaufanieRoute: typeof ZaufanieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zaufanie': {
      id: '/zaufanie'
      path: '/zaufanie'
      fullPath: '/zaufanie'
      preLoaderRoute: typeof ZaufanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zajecia-w-grupie': {
      id: '/zajecia-w-grupie'
      path: '/zajecia-w-grupie'
      fullPath: '/zajecia-w-grupie'
      preLoaderRoute: typeof ZajeciaWGrupieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uzytkowanie-auta': {
      id: '/uzytkowanie-auta'
      path: '/uzytkowanie-auta'
      fullPath: '/uzytkowanie-auta'
      preLoaderRoute: typeof UzytkowanieAutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasza-galeria': {
      id: '/nasza-galeria'
      path: '/nasza-galeria'
      fullPath: '/nasza-galeria'
      preLoaderRoute: typeof NaszaGaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godzina-wyjscia': {
      id: '/godzina-wyjscia'
      path: '/godzina-wyjscia'
      fullPath: '/godzina-wyjscia'
      preLoaderRoute: typeof GodzinaWyjsciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godzina-przyjazdu': {
      id: '/godzina-przyjazdu'
      path: '/godzina-przyjazdu'
      fullPath: '/godzina-przyjazdu'
      preLoaderRoute: typeof GodzinaPrzyjazduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GodzinaPrzyjazduRoute: GodzinaPrzyjazduRoute,
  GodzinaWyjsciaRoute: GodzinaWyjsciaRoute,
  NaszaGaleriaRoute: NaszaGaleriaRoute,
  UzytkowanieAutaRoute: UzytkowanieAutaRoute,
  ZajeciaWGrupieRoute: ZajeciaWGrupieRoute,
  ZaufanieRoute: ZaufanieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
